apiVersion: v1
kind: Service
metadata:
  name: {{ include "secret-agent.fullname" . }}
  labels:
    {{- include "secret-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.webhook.port }}
      targetPort: webhook
      protocol: TCP
      name: webhook
    - port: {{ .Values.service.ports.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "secret-agent.selectorLabels" . | nindent 4 }}
