apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "secret-agent.fullname" . }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "secret-agent.fullname" . }}
      namespace: {{ .Release.Namespace | quote }}
      path: /validate-secret-agent-secrets-forgerock-io-v1alpha1-secretagentconfiguration
  failurePolicy: Fail
  name: vsecretagentconfiguration.kb.io
  rules:
  - apiGroups:
    - secret-agent.secrets.forgerock.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - secretagentconfigurations
  sideEffects: None

