---
appConfig:
  createKubernetesObjects: false
  secretsManager: none  # none, AWS, or GCP
  # gcpProjectID: example-projectID
  # awsRegion: example-region
secrets:
- name: am-boot
  namespace: fr-platform
  keys:
  - name: .keypass
    type: jceks
  - name: .storepass
    type: jceks
  - name: authorized_keys
    type: publicKeySSH
    privateKeyPath: ["amster", "id_rsa"]
- name: am-runtime
  namespace: fr-platform
  keys:
  - name: username
    type: literal
    value: amadmin
  - name: keypass
    type: password
    length: 16
- name: amster
  namespace: fr-platform
  keys:
  - name: id_rsa
    type: privateKey
  - name: authorized_keys
    type: publicKeySSH
    privateKeyPath: ["amster", "id_rsa"]
- name: ds
  namespace: fr-platform
  keys:
  - name: keystore
    type: pkcs12  # jks, jceks
    deployKeyPath: ["ds", "keystore", "deployment-ca"]
    deployKeyPasswordPath: ["ds", "deployment-ca.pin"]
    keyPassPath: ["ds", "keystore.pin"]
    storePassPath: ["ds", "keystore.pin"]
    keystoreAliases:
    - alias: ca-cert
      type: caCert
    - alias: deployment-ca
      type: deploymentKey
    - alias: ssl-key-pair
      type: tlsKeyPair
      commonName: ds
      sans:
      - "*.ds"
      - "*.ds-idrepo"
      - "*.ds-cts"
    - alias: master-key
      type: masterKeyPair
  - name: keystore.pin
    type: password
    length: 32
  - name: deployment-ca.pin
    type: password
    length: 24

