apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: manager
    app.kubernetes.io/name: secret-agent-controller
    app.kubernetes.io/part-of: secret-agent
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: secret-agent-manager
        app.kubernetes.io/part-of: secret-agent
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /manager
        args:
        - --keytoolPath=/usr/local/openjdk-21/bin/keytool
        - --opensslPath=/usr/bin/openssl
        - --webhook-service-ns=$(SERVICE_NAMESPACE)
        - --webhook-service-name=$(SERVICE_NAME)
        - --validating-webhook-name=$(VALIDATING_WEBHOOK_CONFIGURATION_NAME)
        - --mutating-webhook-name=$(MUTATING_WEBHOOK_CONFIGURATION_NAME)
        - --webhook-secret-name=webhook-server-cert
        - --cloud-secrets-namespace=$(SERVICE_NAMESPACE)
        image: controller:latest
        name: manager
        imagePullPolicy: IfNotPresent
        ports:
        - name: webhook-server
          containerPort: 9443
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
