apiVersion: v1
kind: Namespace
metadata:
  name: system
  labels:
    control-plane: controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: manager-service-account
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        - --keytoolPath=/usr/local/openjdk-11/bin/keytool
        - --opensslPath=/usr/bin/openssl
        - --webhook-service-ns=$(SERVICE_NAMESPACE)
        - --webhook-service-name=$(SERVICE_NAME)
        - --webhook-secret-name=webhook-server-cert
        - --validating-webhook-name=$(VALIDATING_WEBHOOK_CONFIGURATION_NAME)
        - --mutating-webhook-name=$(MUTATING_WEBHOOK_CONFIGURATION_NAME) 
        image: controller:latest
        name: manager
        ports:
        - name: webhook-server
          containerPort: 9443
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
      terminationGracePeriodSeconds: 10
