apiVersion: v1
kind: Namespace
metadata:
  name: system
  labels:
    control-plane: controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: manager-service-account
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        - --keytoolPath=/usr/local/openjdk-11/bin/keytool
        - --opensslPath=/usr/bin/openssl
        image: controller:latest
        name: manager
        env:
        - name: SERVICE_NAMESPACE
          value: $(SERVICE_NAMESPACE)
        - name: WEBHOOK_SECRET_NAME
          value: $(WEBHOOK_SECRET_NAME)
        - name: VALIDATING_WEBHOOK_CONFIGURATION
          value: $(VALIDATING_WEBHOOK_CONFIGURATION_NAME)
        - name: MUTATING_WEBHOOK_CONFIGURATION
          value: $(MUTATING_WEBHOOK_CONFIGURATION_NAME) 
        - name: CERTIFICATE_SANS
          value: $(SERVICE_NAME).$(SERVICE_NAMESPACE).svc,$(SERVICE_NAME).$(SERVICE_NAMESPACE).svc.cluster.local
        ports:
        - name: webhook-server
          containerPort: 9443
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
      terminationGracePeriodSeconds: 10
