# permissions for end users to edit secretagentconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretagentconfiguration-editor-role
rules:
- apiGroups:
  - secret-agent.secrets.forgerock.io
  resources:
  - secretagentconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secret-agent.secrets.forgerock.io
  resources:
  - secretagentconfigurations/status
  verbs:
  - get
