---
apiVersion: batch/v1
kind: Job
metadata:
  name: secret-agent
  namespace: default
  labels:
    app: secret-agent
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: secret-agent
        image: gcr.io/forgerock-io/secret-agent:latest
        command:
        - /secret-agent
        - -configFile
        - /etc/secrets-config/secretsConfig.yaml
        volumeMounts:
        - name: secrets-config
          mountPath: /etc/secrets-config
      volumes:
      - name: secrets-config
        configMap:
          name: secrets-config

