# permissions for end users to view secretagentconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretagentconfiguration-viewer-role
rules:
- apiGroups:
  - secret-agent.secrets.forgerock.io
  resources:
  - secretagentconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secret-agent.secrets.forgerock.io
  resources:
  - secretagentconfigurations/status
  verbs:
  - get
