apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      control-plane: controller-manager