---
apiVersion: secret-agent.secrets.forgerock.io/v1alpha1
kind: SecretAgentConfiguration
metadata:
  name: forgerock-sac
spec:
  appConfig:
    createKubernetesObjects: true
    secretsManager: none  # none, AWS, or GCP
    # gcpProjectID: example-projectID
    # awsRegion: example-region
    # azureVaultName: example-vault
  secrets:
  - name: platform-ca
    keys:
    - name: ca
      type: ca
      spec:
        distinguishedName:
          commonName: platform-ca

  - name: vault-secrets
    keys:
    - name: vault-ca
      type: ca
      spec:
        distinguishedName:
          commonName: vault-secrets

  - name: amster-ssh
    keys:
    - name: id_rsa
      type: ssh

  - name: ds-env-secrets
    keys:
      - name: dirmanager.pw
        type: password
        spec:
          length: 32
      - name: monitor.pw
        type: literal
        spec:
          value: prometheus

  - name: ds
    keys:
    - name:  ssl-key-pair
      type: keyPair
      spec:
        algorithm: ECDSAWithSHA256
        distinguishedName:
          commonName: ds
        sans:
        - "*.ds"
        - "*.ds-idrepo"
        - "*.ds-cts"
        signedWithPath: platform-ca/ca # json path to a secret + key
    - name: master-key-pair
      type: keyPair
      spec:
        algorithm: SHA256WithRSA
        distinguishedName:
          commonName: master-key
        signedWithPath: platform-ca/ca
    - name: keystore.pin 
      type: password     
    - name: keystore.p12
      type: keytool
      spec:
        storeType: pkcs12
        storePassPath: ds/keystore.pin
        keyPassPath: ds/keystore.pin
        keytoolAliases:
          - name: ca-cert
            cmd: importcert
            sourcePath: "platform-ca/ca"
          - name: ssl-keypair
            cmd: importcert
            sourcePath: "ds/ssl-key-pair"
          - name: master-keypair
            cmd: importcert
            sourcePath: "ds/master-key-pair"

  - name: am-passwords
    keys:
    - name: .keypass
      type: password
    - name: .storepass
      type: password
    - name: username
      type: literal
      spec:
        value: amadmin

  - name: am-keystore
    keys:
    - name: keystore.jceks
      type: keytool
      spec:
        storeType: jceks
        storePassPath: am-passwords/.storepass
        keyPassPath: am-passwords/.keypass
        keytoolAliases:
          - name: rsajwtsigningkey
            cmd: genkeypair
            args: ["-keyalg", "RSA", "-keysize", "2048", "-validity", "7300"]
            destinationPath: truststore/cacerts
          - name: ec256test
            cmd: genkeypair
            args : ["-keyalg", "EC","-sigalg",  "SHA256withECDSA", "-dname", "CN=ForgeRock", "-keysize", "256"]
            destinationPath: truststore/cacerts
          - name: hmacsigningtest
            cmd: genseckey
            args: ["-keyalg", "HMacSHA512", "-keysize", "512"]
            destinationPath: truststore/cacerts
          - name: configstorepwd
            cmd: importpassword
            sourcePath: am-passwords/.storepass
          - name: my-imported-cert
            cmd: importcert
            sourcePath: truststore/cacerts
      
  - name: truststore
    keys:
    - name: cacerts
      type: truststore
      spec:
        truststoreImportPaths: ["platform-ca/ca", "vault-secrets/vault-ca"]
