---
apiVersion: secret-agent.secrets.forgerock.io/v1alpha1
kind: SecretAgentConfiguration
metadata:
  name: standard-forgerock-example
  namespace: default
spec:
  appConfig:
    createKubernetesObjects: true
    secretsManager: none  # none, AWS, or GCP
    # gcpProjectID: example-projectID
    # awsRegion: example-region
    # azureVaultName: example-vault
  secrets:
  - name: am-boot
    keys:
    - name: .keypass
      type: jceks
    - name: .storepass
      type: jceks
    - name: authorized_keys
      type: publicKeySSH
      privateKeyPath: ["amster", "id_rsa"]
  - name: am-runtime
    keys:
    - name: username
      type: literal
      value: amadmin
    - name: keypass
      type: password
      length: 16
  - name: amster
    keys:
    - name: id_rsa
      type: privateKey
    - name: authorized_keys
      type: publicKeySSH
      privateKeyPath: ["amster", "id_rsa"]
  - name: platform-ca-private
    keys:
    - name: ca
      type: ca
    - name: private-key
      type: caPrivateKey
      caPath: ["platform-ca-private", "ca"]
  - name: platform-ca-public
    keys:
    - name: public-key
      type: caPublicKey
      privateKeyPath: ["platform-ca-private", "private-key"]
  - name: ds
    keys:
    - name: keystore
      type: pkcs12  # jks, jceks
      storePassPath: ["ds", "keystore.pin"]
      keyPassPath: ["ds", "keystore.pin"]
      keystoreAliases:
      - alias: ca-cert
        type: pemPublicKeyCopy
        publicKeyPath: ["platform-ca-public", "public-key"]
      - alias: ssl-key-pair
        type: keyPair  # hmacKey, aesKey
        algorithm: ECDSAWithSHA256
        commonName: ds
        sans:
        - "*.ds"
        - "*.ds-idrepo"
        - "*.ds-cts"
        signedWithPath: ["platform-ca-private", "ca"]
      - alias: master-key-pair
        type: keyPair
        algorithm: SHA256withRSA
        commonName: master-key
        signedWithPath: ["platform-ca-private", "private-key"]
    - name: keystore.pin
      type: password
      length: 32

