---
apiVersion: secret-agent.secrets.forgerock.io/v1alpha1
kind: SecretAgentConfiguration
metadata:
  name: forgerock-sac
spec:
  appConfig:
    createKubernetesObjects: true
    secretsManager: none  # none, AWS, or GCP
    # gcpProjectID: example-projectID
    # awsRegion: example-region
    # azureVaultName: example-vault
  secrets:
  - name: platform-ca
    keys:
    - name: ca
      type: ca
      spec:
        distinguishedName:
          commonName: platform-ca

  - name: vault-secrets
    keys:
    - name: vault-ca
      type: ca
      spec:
        distinguishedName:
          commonName: vault-secrets

  - name: amster-ssh
    keys:
    - name: id_rsa
      type: ssh

  - name: ds-env-secrets
    keys:
      - name: dirmanager.pw
        type: password
        spec:
          length: 32
      - name: monitor.pw
        type: literal
        spec:
          value: prometheus

  - name: ds
    keys:
    - name:  ssl-key-pair
      type: keyPair
      spec:
        algorithm: ECDSAWithSHA256
        distinguishedName:
          commonName: ds
        sans:
        - "*.ds"
        - "*.ds-idrepo"
        - "*.ds-cts"
        signedWithPath: platform-ca/ca # json path to a secret + key
    - name: master-key-pair
      type: keyPair
      spec:
        algorithm: SHA256WithRSA
        distinguishedName:
          commonName: master-key
        signedWithPath: platform-ca/ca
    - name: keystore.pin
      type: password
    - name: keystore.p12
      type: keytool
      spec:
        storeType: pkcs12
        storePassPath: ds/keystore.pin
        keyPassPath: ds/keystore.pin
        keytoolAliases:
          - name: ca-cert
            cmd: importcert
            sourcePath: "platform-ca/ca"
          - name: ssl-keypair
            cmd: importcert
            sourcePath: "ds/ssl-key-pair"
          - name: master-keypair
            cmd: importcert
            sourcePath: "ds/master-key-pair"

  - name: am-passwords
    keys:
    - name: .keypass
      type: password
    - name: .storepass
      type: password
    - name: username
      type: literal
      spec:
        value: amadmin

  - name: idm-env-secrets
    keys:
    - name: OPENIDM_ADMIN_PASSWORD
      type: password
    - name: OPENIDM_KEYSTORE_PASSWORD
      type: password
    - name: OPENIDM_REPO_PASSWORD
      type: password
    - name: RS_CLIENT_SECRET
      type: password
    - name: USERSTORE_PASSWORD
      type: password

  - name: am-keystore
    keys:
    - name: keystore.jceks
      type: keytool
      spec:
        storeType: jceks
        storePassPath: am-passwords/.storepass
        keyPassPath: am-passwords/.keypass
        keytoolAliases:
        - name: rsajwtsigningkey
          cmd: genkeypair
          args: ["-keyalg", "RSA", "-keysize", "2048", "-sigalg", "SHA256WITHRSA", "-validity", "3650", "-dname", "CN=rsajwtsigningkey,O=ForgeRock,L=Bristol,ST=Bristol,C=UK"]
        - name: ec256test
          cmd: genkeypair
          args: ["-keyalg", "EC", "-keysize", "256", "-sigalg", "SHA256withECDSA", "-validity", "3650", "-dname", "CN=es256test,O=ForgeRock,L=Bristol,ST=Bristol,C=UK"]
        - name: es384test
          cmd: genkeypair
          args: ["-keyalg", "EC", "-keysize", "384", "-sigalg", "SHA256withECDSA", "-validity", "3650", "-dname", "CN=es384test,O=ForgeRock,L=Bristol,ST=Bristol,C=UK"]
        - name: es512test
          cmd: genkeypair
          args: ["-keyalg", "EC", "-keysize", "512", "-sigalg", "SHA256withECDSA", "-validity", "3650", "-dname", "CN=es512test,O=ForgeRock,L=Bristol,ST=Bristol,C=UK"]
        - name: selfserviceenctest
          cmd: genkeypair
          args: ["-keyalg", "RSA", "-keysize", "2048", "-sigalg", "SHA256WITHRSA", "-validity", "3650", "-dname", "CN=selfserviceenctest,O=ForgeRock,L=Bristol,ST=Bristol,C=UK"]
        - name: test
          cmd: genkeypair
          args: ["-keyalg", "RSA", "-keysize", "2048", "-sigalg", "SHA256WITHRSA", "-validity", "3650", "-dname", "CN=test,O=ForgeRock,L=Bristol,ST=Bristol,C=UK"]
        - name: hmacsigningtest
          cmd: genseckey
          args: ["-keyalg", "HMacSHA512", "-keysize", "512"]
        - name: selfservicesigntest
          cmd: genseckey
          args: ["-keyalg", "HMacSHA512", "-keysize", "256"]
        - name: directenctest
          cmd: genseckey
          args: ["-keyalg", "aes", "-keysize", "256"]
        - name: configstorepwd
          cmd: importpassword
          sourcePath: am-passwords/.storepass
        - name: dsameuserpwd
          cmd: importpassword
          sourcePath: ds-env-secrets/dirmanager.pw
        - name: my-imported-cert
          cmd: importcert
          sourcePath: truststore/cacerts
        # TODO
        # keytool -importkeystore -destalias sms.transport.key -srcalias sms.transport.key -srcstoretype jceks -srckeystore sms-transport-key/sms-transport-key.jceks -srckeypass:file sms-transport-key/keypass -srcstorepass:file sms-transport-key/storepass -destkeystore /opt/gen/secrets/generic/am-keystore/keystore.jceks -deststoretype jceks -deststorepass zzggthedwwd4pegt1tth02drmxfbdw01 -destkeypass is4spw1bfagasmsc0gpgd2gwrgrzchz0
    - name: truststore
      type: truststore
      spec:
        #TODO. Verify truststore value
        truststoreImportPaths: ["platform-ca/ca"]

  - name: idm
    keys:
    - name: keystore.jceks
      type: keytool
      spec:
        storeType: jceks
        storePassPath: am-passwords/.storepass
        keyPassPath: am-passwords/.keypass
        keytoolAliases:
        - name: openidm-sym-default
          cmd: genseckey
          args: ["-keyalg", "aes", "-keysize", "128"]
        - name: openidm-jwtsessionhmac-key
          cmd: genseckey
          args: ["-keyalg", "HmacSHA256", "-keysize", "256"]
        - name: openidm-selfservice-key
          cmd: genseckey
          args: ["-keyalg", "aes", "-keysize", "128"]
        - name: server-cert 
          cmd: genkeypair
          args: ["-keyalg", "RSA", "-keysize", "2048", "-sigalg", "SHA256WITHRSA", "-validity", "3650", "-dname", "CN=server-cert,O=ForgeRock,L=Bristol,ST=Bristol,C=UK"]
        - name: selfservice
          cmd: genkeypair
          args: ["-keyalg", "RSA", "-keysize", "2048", "-sigalg", "SHA256WITHRSA", "-validity", "3650", "-dname", "CN=selfservice,O=ForgeRock,L=Bristol,ST=Bristol,C=UK"]
        - name: openidm-localhost
          cmd: genkeypair
          args: ["-keyalg", "RSA", "-keysize", "2048", "-sigalg", "SHA256WITHRSA", "-validity", "3650", "-dname", "CN=openidm-localhost,O=ForgeRock,L=Bristol,ST=Bristol,C=UK"]
  
  - name: truststore
    keys:
      - name: cacerts
        type: truststore
        spec:
          # truststoreImportPaths: ["platform-ca/ca", "vault-secrets/vault-ca"]
          truststoreImportPaths: ["platform-ca/ca"]
