---
apiVersion: secret-agent.secrets.forgerock.io/v1alpha1
kind: SecretAgentConfiguration
metadata:
  name: standard-forgerock-example
  namespace: default
spec:
  appConfig:
    createKubernetesObjects: true
    secretsManager: none  # none, AWS, or GCP
    # gcpProjectID: example-projectID
    # awsRegion: example-region
    # azureVaultName: example-vault
  secrets:
  - name: am-runtime-passwords
    keys:
      - name: keypassruntime
        type: password
        length: 24
      - name: storepassruntime
        type: password
        length: 24
  - name: amster-env-secrets
    keys:
      - name: AM_ENC_KEY
        type: password
        length: 32
      - name: AM_POLICY_AGENT_PASS
        type: password
        length: 24
      - name: AMADMIN_PASS
        type: password
        length: 24
      - name: CFGDIR_PASS
        type: password
        length: 24
      - name: CFGUSR_PASS
        type: password
        length: 24
      - name: CTSDIR_PASS
        type: password
        length: 24
      - name: CTSUSR_PASS
        type: password
        length: 24
      - name: IDM_PROVISIONING_CLIENT_SECRET
        type: password
        length: 24
      - name: IDM_RS_CLIENT_SECRET
        type: password
        length: 24
      - name: USRDIR_PASS
        type: password
        length: 24
      - name: USRUSR_PASS
        type: password
        length: 24
  - name: ds-passwords
    keys:
      - name: dirmanager.pw
        type: password
        length: 32
      - name: monitor.pw
        type: password
        length: 32
  - name: am-boot-secrets
    keys:
    - name: .keypass
      type: jceks
    - name: .storepass
      type: jceks
    - name: authorized_keys
      type: publicKeySSH
      privateKeyPath: ["amster", "id_rsa"]
    - name: username
      type: literal
      value: amadmin
    - name: keypass
      type: password
      length: 16
  - name: amster
    keys:
    - name: id_rsa
      type: privateKey
    - name: authorized_keys
      type: publicKeySSH
      privateKeyPath: ["amster", "id_rsa"]
  - name: truststore
    keys:
    - name: cacerts
      type: truststore
      keyStorePath: ["truststore", "cacerts-keypin"]
      storePassPath: ["truststore", "cacerts-keypin"]
      keystoreAliases:
        - alias: ca-cert
          type: caCopy
          caPath: ["platform-ca-public", "public-key"]
    - name: cacerts-keypin
      type: literal
      value: changeit
  - name: platform-ca-private
    keys:
    - name: ca
      type: ca
    - name: private-key
      type: caPrivateKey
      caPath: ["platform-ca-private", "ca"]
  - name: platform-ca-public
    keys:
    - name: public-key
      type: caCopy
      caPath: ["platform-ca-private", "ca"]
  - name: ds
    keys:
    - name: keystore
      type: pkcs12  # jks, jceks
      storePassPath: ["ds", "keystore.pin"]
      keyPassPath: ["ds", "keystore.pin"]
      keystoreAliases:
      - alias: ca-cert
        type: caCopy
        caPath: ["platform-ca-public", "public-key"]
      - alias: ssl-key-pair
        type: keyPair  # hmacKey, aesKey
        algorithm: ECDSAWithSHA256
        commonName: ds
        sans:
        - "*.ds"
        - "*.ds-idrepo"
        - "*.ds-cts"
        signedWithPath: ["platform-ca-private", "private-key"]
      - alias: master-key
        type: keyPair
        algorithm: SHA256WithRSA
        commonName: master-key
        selfSigned: true
        expire: 1
    - name: keystore.pin
      type: password
      length: 32

