name: CI
on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master]

jobs:
  basic-checks:
    name: Run basic-checks
    runs-on: ubuntu-latest
    # container: golang:1.14-buster
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: go-fmt
      run: go fmt ./...

    - name: Check for uncommited formatting
      run: if [ -n "$(git status --untracked-files=no --porcelain)" ]; then echo "There are uncommitted changes"; exit 1; fi
    
    - name: Run unit tests
      run: go test ./... -cover
    
  integration-tests:
    name: Run integration-tests
    needs: basic-checks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
       
    - name: Build Test Image
      run: docker build -t secret-agent-tester --target=tester .

    - name: Test
      run: docker run -i --rm -v ${GITHUB_WORKSPACE}:/root/go/src/github.com/ForgeRock/secret-agent secret-agent-tester make citest

  build:
    name: Build Pull Request Binaries
    needs: integration-tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Set Go Releaser Environment
      run: |
        echo "GIT_DIRTY="$(test -n "`git status --porcelain`" && echo "+CHANGES" || true) >> $GITHUB_ENV
        echo "VERSION="$(grep "var Version " pkg/version/version.go | awk -F " = " -F '"' '{ print $2 }') >> $GITHUB_ENV
        echo "BUILD_DATE="$(date '+%Y-%m-%d-%H:%M:%S') >> $GITHUB_ENV
    - name: Build Snapshot
      if: ${{ github.event_name == 'pull_request' }}
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: --snapshot --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG_NAME: ${{ env.VERSION }}-pr.${{ github.event.pull_request.number }}
        GIT_COMMIT: ${{ github.sha }} 
        IMAGE_NAME: "forgerock/secret-agent"
 
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: dist/*.tar.gz
