name: Go
on:
  push:
    branches: [ master, refactor ]
  pull_request:
    branches: [ master, refactor ]

jobs:
  basic-checks:
    name: Run basic-checks
    runs-on: ubuntu-latest
    # container: golang:1.14-buster
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: go-fmt
      run: go fmt ./...

    - name: Check for uncommited formatting
      run: if [ -n "$(git status --untracked-files=no --porcelain)" ]; then echo "There are uncommitted changes"; exit 1; fi
    
    - name: Run unit tests
      run: go test ./... -cover
    
  integration-tests:
    name: Run integration-tests
    needs: basic-checks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
       
    - name: Build Test Image
      run: docker build -t secret-agent-tester --target=tester .

    - name: Test
      run: docker run -i --rm -v ${GITHUB_WORKSPACE}:/root/go/src/github.com/ForgeRock/secret-agent secret-agent-tester make citest

